[package]

name = "plex"
version = "0.0.3"
authors = ["Geoffry Song <goffrie@gmail.com>"]

description = "A syntax extension for writing lexers and parsers."
homepage = "https://github.com/goffrie/plex"
repository = "https://github.com/goffrie/plex"
documentation = "http://goffrie.github.io/plex"
license = "MIT OR Apache-2.0"
keywords = ["tokenizer", "scanner", "lexer", "parser", "generator"]

[lib]

name = "plex"
plugin = true
crate-type = ["dylib"]

[dependencies]

lalr = "0.0.2"
redfa = "0.0.2"
